### ISSUE TITLE
Method ShortsControllerSettings() can't be called even youtube_shorts.dart is imported

### ISSUE THREAD

**Issue by accept1248** [igormidev/youtube_shorts#3]
First of all, I can't set the property 'startWithAutoplay'  like the following example.
final ShortsController controller = ShortsController(
  startWithAutoplay: false, // Default is true
  ...
);

Adding to that, I want to set startWithAutoplay = false for ShortsController, but cannot call ShortsControllerSettings().
Here is the error message
The method 'ShortsControllerSettings' isn't defined.
Try correcting the name to the name of an existing method, or defining a method named 'ShortsControllerSettings'.

Of course I imported 'package:youtube_shorts/youtube_shorts.dart', but this error occurs.

Doesn't this happen in your environment?

**Comment by accept1248** [comment]
Hey, simply add export 'src/data/shorts_controller_settings.dart' to youtube_shorts/youtube_shorts.dart 

library youtube_shorts;

export 'src/logic/shorts_controller.dart';
export 'src/logic/shorts_state.dart';
export 'src/source/interface_videos_source_controller.dart';
export 'src/data/type_defs.dart';
export 'src/data/not_focused_ui_type.dart';
export 'src/data/shorts_controller_settings.dart';
export 'src/ui/youtube_shorts_page.dart';
export 'src/ui/youtube_shorts_horizontal_stories_section.dart';

export 'package:media_kit/media_kit.dart' show MediaKit;
export 'package:media_kit_video/media_kit_video.dart'
    show VideoController, VideoControllerConfiguration;
export 'youtube_explode_fork/youtube_explode_dart.dart'
    show Video, MuxedStreamInfo;

**Comment by igormidev** [comment]
Wow, man! So sorry for the time to replying 🙏 
Github did not notified me that someone had opened an issue..

I fixed the problem you related in [version 4.0.0](https://pub.dev/packages/youtube_shorts). 
(Also introduced ads possibility :D)

Please update your dependency and let me now if the problem is now resolved. I'll stay in wait for further updates.

**Comment by igormidev** [comment]
Closing issue due to lack of response
